# src/application/config/assets/multimedia_models.yaml
# 资源模型配置 - 优化版

assets:
  audio:
    description: "AI音频生成"
    default_provider: "replicate"
    providers:
      replicate:
        models:
          ardianfe:
            model_id: "ardianfe/musicgen-stereo-chord:latest"
            description: "高质量立体声音乐生成"
            max_duration: 300
            output_format: "wav"
            
          meta:
            model_id: "meta/musicgen:latest"
            description: "Meta MusicGen音乐生成"
            max_duration: 600
            output_format: "wav"
    
    generation_limits:
      max_outputs_per_request: 5
      default_timeout: 600
      
  animation:
    description: "AI动画生成"
    default_provider: "replicate"
    providers:
      replicate:
        models:
          pixverse:
            model_id: "pixverse/pixverse:latest"
            description: "文本到动画生成"
            max_duration: 8
            output_format: "mp4"
            
          pia:
            model_id: "ali-vilab/i2vgen-xl:latest"
            description: "图片到动画生成"
            max_duration: 24
            output_format: "mp4"
    
    generation_limits:
      max_outputs_per_request: 3
      default_timeout: 900
      
  video:
    description: "AI视频处理"
    default_provider: "replicate"
    providers:
      replicate:
        models:
          background_removal:
            model_id: "arielreplicate/remove_video_background:latest"
            description: "视频背景移除"
            max_duration: 300
            output_format: "mp4"
    
    generation_limits:
      max_outputs_per_request: 2
      default_timeout: 1200

# 全局配置
global_generation_config:
  max_concurrent_generations: 5
  default_queue_priority: 1
  cleanup_temp_files: true
  temp_file_retention_hours: 24